name: Release libs

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
 
jobs:
  build:
    name: Release libs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14]

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --manifest-path src-rust/Cargo.toml

    - name: Correct MacOS lib name
      if: runner.os == 'MacOS'
      run: |
        mv src-rust/target/release/libpty.dylib libpty_$(uname -m).dylib

    - name: Upload MacOS lib
      if: runner.os == 'Linux'
      uses: svenstaro/upload-release-action@v2
      with:
        file: libpty_*.dylib
        tag: ${{ github.ref }}
        overwrite: true
        file_globe: true

    - name: Upload Linux lib
      if: runner.os == 'Linux'
      uses: svenstaro/upload-release-action@v2
      with:
        file: src-rust/target/release/libpty.so
        tag: ${{ github.ref }}
        overwrite: true

    - name: Upload Windows lib
      if: runner.os == 'Windows'
      uses: svenstaro/upload-release-action@v2
      with:
        file: src-rust/target/release/pty.dll
        tag: ${{ github.ref }}
        overwrite: true
